version: '3.7'
services:
    postgres:
      image: postgres
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_Db=moviedb
      ports:
        - 5432:5432
      logging:
        options:
          max-size: 10m
          max-file: "3"
    pgadmin:
      image: dpage/pgadmin4
      environment:
        - PGADMIN_DEFAULT_EMAIL=root@gmail.com
        - PGADMIN_DEFAULT_PASSWORD=Secret_Tunnel
      ports:
        - "5050:80"